LOTTO_GAMES = {
    "loto6": {
        "display_name": "LOTO6",
        "kind": "loto6",
        "pick_count": 6,
        "min_num": 1,
        "max_num": 43,
        "main_cols": [
            "main1",
            "main2",
            "main3",
            "main4",
            "main5",
            "main6",
        ],
        "bonus_cols": ["bonus"],
        "train_window": 500,
        "tested_periods": 45,
        "backtest_candidates": 300,
        "final_candidates": 10000,
        "prediction_filename": "prediction_optimizer_loto6.json",
    },
    "loto7": {
        "display_name": "LOTO7",
        "kind": "loto7",
        "pick_count": 7,
        "min_num": 1,
        "max_num": 37,
        "main_cols": [
            "main1",
            "main2",
            "main3",
            "main4",
            "main5",
            "main6",
            "main7",
        ],
        "bonus_cols": ["bonus1", "bonus2"],
        "train_window": 240,
        "tested_periods": 45,
        "backtest_candidates": 300,
        "final_candidates": 10000,
        "prediction_filename": "prediction_optimizer_loto7.json",
    },
    "miniloto": {
        "display_name": "MINILOTO",
        "kind": "miniloto",
        "pick_count": 5,
        "min_num": 1,
        "max_num": 31,
        "main_cols": [
            "main1",
            "main2",
            "main3",
            "main4",
            "main5",
        ],
        "bonus_cols": ["bonus"],
        "train_window": 400,
        "tested_periods": 45,
        "backtest_candidates": 300,
        "final_candidates": 10000,
        "prediction_filename": "prediction_optimizer_miniloto.json",
    },
}